### PR TITLE
replace parentheses with static button

### PR DESCRIPTION
**Pull request by AdrienFabre**

### CODE REVIEW

**Review by dangroze — APPROVED** [review]

**Comment by dippedincode** [comment]
I disagree with this change. The () brackets were absolutely fine - it fits with the text of the column heading. Now it looks like a button - in fact it is named static button, and it looks separate from the column heading. I clicked it thinking something would happen, no.
Can you give a reason for this idea?

**Comment by dippedincode** [comment]
card-count-boxes
Adding an image of the suggested card count boxes. They look separate and misaligned from the column heading in my view.

**Comment by david-mears** [comment]
I think this looks pretty slick, personally. However, in the interests of productive disagreement, let me propose a compromise. To resolve Diptis' complaint that the column headings are now un-centered, and to preserve the minimalist, uncluttered design, put the card count in the top right corner of the column. I attach an image - I've put this in a branch called [CardsCount-top-right](https://github.com/what-zen/what-zen-app/pull/34).

My solution also has the advantage of making the code DRYer - I only render `<CardsCount>` once, on line 122 of [CardList/index.js](https://github.com/what-zen/what-zen-app/blob/aa9869da7943102ccce42646880a7d8900a77069/src/components/CardList/index.js)

image

I made a pull request [here](https://github.com/what-zen/what-zen-app/pull/34)

**Comment by dangroze** [comment]
I like the compromise version.

**Review by david-mears — CHANGES_REQUESTED** [review]
(clicking 'request changes' in order to require agreement before merging)

**Review by dangroze — CHANGES_REQUESTED** [review]
I don't have a strong opinion about any of the 3 versions, so whatever pleases everyone!

**Comment by dippedincode** [comment]
I approve the compromise deal proposed by David Mears. Yes, looks slick that, very zen.
I'll approve amendment #34

**Pull request merged**
